# Generated by Django 3.2.5 on 2021-07-26 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hood', '0002_auto_20210726_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='Admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
