# Generated by Django 3.2.5 on 2021-07-26 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighbourbood',
            new_name='neighbourhood',
        ),
    ]
